[keyboard]
name = "Split65_Left"
product_name = "Split65"
vendor_id = 0x4C4B
product_id = 0x4643
manufacturer = "Nathan"
chip = "nrf52840"

[host]
vial_enabled = true
unlock_keys = [[2,2]]

[ble]
enabled = true
battery_adc_pin = "vddh"
adc_divider_measured = 2000
adc_divider_total = 2806
default_tx_power = 0

[split]
connection = "ble"
central = true

[matrix]
row_pins = ["P0_17","P0_20","P0_22","P1_00","P0_11","P1_04"]
col_pins = ["P0_09","P0_10","P0_29","P0_31","P1_01","P1_02","P1_07"]
row2col = true
