[keyboard]
name = "Split65"
product_name = "Split65"
vendor_id = 0x4C4B
product_id = 0x4643
manufacturer = "Nathan"
chip = "nrf52840"

[host]
vial_enabled = true
unlock_keys = [[2,2]]

[ble]
enabled = true
battery_adc_pin = "vddh"
adc_divider_measured = 2000
adc_divider_total = 2806
default_tx_power = 0

[split]
connection = "ble"

[split.central]
rows = 6
cols = 7
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_17","P0_20","P0_22","P1_00","P0_11","P1_04"]
col_pins = ["P0_09","P0_10","P0_29","P0_31","P1_01","P1_02","P1_07"]
row2col = true

[[split.peripheral]]
rows = 6
cols = 9
row_offset = 0
col_offset = 7

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_17","P0_20","P0_22","P1_00","P0_11","P1_04"]
col_pins = ["P0_09","P0_10","P0_29","P0_31","P1_07","P1_02","P1_01","P1_13","P1_11"]
row2col = true

[layout]
rows = 6
cols = 16

map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9) (0,10) (0,11) (0,12) (0,13) (0,14) (0,15)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9) (1,10) (1,11) (1,12) (1,13) (1,14) (1,15)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9) (2,10) (2,11) (2,12) (2,13) (2,14) (2,15)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8) (3,9) (3,10) (3,11) (3,12) (3,13) (3,14) (3,15)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5) (4,6) (4,7) (4,8) (4,9) (4,10) (4,11) (4,12) (4,13) (4,14) (4,15)
(5,0) (5,1) (5,2) (5,3) (5,4) (5,5) (5,6) (5,7) (5,8) (5,9) (5,10) (5,11) (5,12) (5,13) (5,14) (5,15)
"""

[keymap]

[[keymap.layer]]
name = "Base"

keys = """
Escape F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 Delete PageUp PageDown
Grave 1 2 3 4 5 6 7 8 9 0 Minus Equal _ Backspace _
Tab Q W E R T Y U I O P LeftBracket RightBracket _ Enter _
CapsLock A S D F G H J K L Semicolon Quote _ _ _
LeftShift Z X C V B N M Comma Dot Slash _ UpArrow _ _
LeftCtrl LeftGui LeftAlt _ Space _ RightAlt Menu _ _ LeftArrow DownArrow RightArrow _ _
"""
